# RJ Hunter
# AD 440
# Cloud Practicum
# 
# file contains method to call twitter api and verify credentials of the
# app user.   
# 

import requests
import json
from requests_oauthlib import OAuth1

# method calls twitter api and verifys a user's credentials.  The method
# will return a HTTP status code (200 for success, 401 for error). The
# method uses 2 parameters (access token, access token secret). The
# access token and secret are generated by the web/mobile client when
# logging into the app using twitter. These parameters will be handed
# to the server side api when making any requests.
def verify_oauth(access_token,access_token_secret):
    # consumer key and secret.  these keys are generated when creating
    # our twitter app on the twitter developer portal.  They are needed
    # when verifing twitter credentials 
    consumer_key='kbwf3Qbb6MfjXiPirco5j3UYe'
    consumer_secret='1Lr0HOTxQBLU22FsH2CH9RFBtnQCHwjAsidZrctvYoy9yIDX7n'

    # url of twitter api that verifys a users credentials
    url = 'https://api.twitter.com/1.1/account/verify_credentials.json'
    # oAuth1 method that creates an authorization object to hand to
    # twitters api
    auth = OAuth1(consumer_key, consumer_secret, access_token, access_token_secret)

    # gets request from twitter api
    # returns json result from request
    return requests.get(url, auth=auth)

# main method
def main():
    
    # access token and secret are generated by the web client.  These tokens are used
    # to verify user's credentials 
    access_token='4800385332-ZbrU1XfignI2lA3MjQu7U8KbIkTdYAdj1ArMVFR'
    access_token_secret='BPSs4gwICptsGVZQc9F2EpWcw6ar1gsv4Nlnqvq5PFIdF'
    # call method and print result
    #print(verify_oauth(access_token,access_token_secret))
    tom = verify_oauth(access_token,access_token_secret)
    print(tom.status_code)
# call main
if __name__ == "__main__":
    main()
